import React, { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/header/header'
import SideNavi from '../components/navi/sideNavi'
import Top from '../components/main/Top/Top'
import About from '../components/main/About/About'
import Portfolio from '../components/main/portfolios/Portfolio'
import Contact from '../components/main/Contact/Contact'

export default function Home() {

  const [openState, setOpenState] = useState<boolean>(false);

  const chengeOpenState = () => {
    setOpenState(!openState);
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Take’s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:300" rel="stylesheet" />
      </Head>

      <Header chengeOpenState={chengeOpenState} />
      <SideNavi openState={openState} chengeOpenState={chengeOpenState} />
      <main className={styles.main}>
        <Top />
        <About />
        <Portfolio />
        <Contact />
      </main>

      <footer className={styles.footer}>
        <h3>
          © 2021 Takeshi.T
        </h3>
      </footer>
    </div>
  )
}
